name: flutter_z_location_mz
description: A new GPS and IP Location library.
version: 0.1.0
homepage: https://github.com/zenganiu/flutter_z_location_mz

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  maps_toolkit: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_z_location_mz
        pluginClass: FlutterZLocationPlugin
      ios:
        pluginClass: FlutterZLocationPlugin

